### ISSUE TITLE
Can't create a sivafs to read siva files from my readonly volume

### ISSUE THREAD

**Issue by eiso** [src-d/go-billy-siva#23]
Expected behavior: I can create a sivafs to read siva files from my readonly volume

When creating a billy filesystem for reading siva files, the `fs.underlying.OpenFile` sets the permissions to be readwrite/create. https://github.com/src-d/go-billy-siva/blob/e653a4a07db145ffcdc9c43f40099ba598987237/filesystem.go#L255

I recommend to make this a flag. I came across this because I was using a Google Cloud persistent disk that only allows for ReadMany permissions.

**Comment by vmarkovtsev** [comment]
@smola I miss this feature too.

**Comment by smola** [comment]
In order to keep backwards compatibility, I would suggest to add a new function `NewFilesystemReadOnly`. If, at some point, we add the ability to signal read-only filesystems in `go-billy`, then we could make the default `NewFilesystem` to autodetect this.
