### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/go-billy-siva#29]
The following code fails on Windows

```go
localFs := osfs.New(filepath.Dir("c:\\path\\to\\file.siva"))
tmpFs := memfs.New()
fs, err := sivafs.NewFilesystem(localFs, "file.siva", tmpFs)
if err != nil {
	log.Panicf("unable to create a siva filesystem from %s: %v", uri, err)
}
sivaStorage, err := filesystem.NewStorage(fs)
if err != nil {
	log.Panicf("unable to create a new storage backend for siva file %s: %v", uri, err2)
}
repository, err = git.Open(sivaStorage, tmpFs)
if err != nil {
        log.Panicf("git.Open: %v", err)
}
```

It panics on the very last step `git.Open` with `repository does not exist`. An example in the wild: https://ci.appveyor.com/project/vmarkovtsev/hercules/build/174#L288 (the directory listing is a few lines above). File to test: https://github.com/vmarkovtsev/hercules/blob/master/cmd/hercules/test_data/hercules.siva

**Comment by vmarkovtsev** [comment]
CC @smola

**Comment by smola** [comment]
cc @jfontan

**Comment by jfontan** [comment]
Waiting for src-d/go-siva#40
